
name: test-workflow01

on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  job01:
    runs-on: ubuntu-22.04
    steps:
      - name: step01
        run: echo "Hello GitHub!"
      - name: step02
        run: |
          echo "Second step..."
          echo "same as the first!"
